---

- name: Detect CPU frequency driver
  command: cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver
  register: cpu_driver
  changed_when: false

- name: Create CPU power management systemd service
  ansible.builtin.template:
    src: cpu_power.service.j2
    dest: /etc/systemd/system/{{ service_name }}
  when: "'pstate' in cpu_driver.stdout"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  when: "'pstate' in cpu_driver.stdout"

- name: Enable and start CPU power management service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    enabled: true
    state: started
  when: "'pstate' in cpu_driver.stdout"

- name: Discover battery directories (BAT*)
  ansible.builtin.command: "ls -d /sys/class/power_supply/BAT*"
  changed_when: false
  ignore_errors: true
  register: battery_dirs_raw

- name: Normalize battery directories list
  ansible.builtin.set_fact:
    battery_dirs: "{{ battery_dirs_raw.stdout_lines | default([]) }}"

- name: Check for charge_control_end_threshold on each battery
  ansible.builtin.stat:
    path: "{{ item.path }}/charge_control_end_threshold"
  with_items: "{{ battery_dirs.files }}"
  register: battery_thresholds

- name: Set charge limit to 60% where supported
  ansible.builtin.command:
    cmd: "sh -c 'echo 60 > {{ item.item.path }}/charge_control_end_threshold'"
  when: item.stat.exists
  loop: "{{ battery_thresholds.results }}"