---

- name: Install cluster
  include_tasks: install_cluster/main.yml
  when: cluster_state == 'present'

- name: Destroy cluster
  include_tasks: destroy_cluster.yml
  when: cluster_state == 'absent'