---

cluster_name: homelab-cluster

scaling_governor: powersave
EPP: balance_power

packages:
  - python3
  - python3-apt
  - powerstat
  - powertop
  - lm-sensors

debian_repos:
  # --- Proxmox No-Subscription Repo ---
  - repo: "deb http://download.proxmox.com/debian/pve {{ ansible_facts['distribution_release'] }} pve-no-subscription"
    gpg_key: "https://enterprise.proxmox.com/debian/proxmox-release-{{ ansible_facts['distribution_release'] }}.gpg"
    filename: "pve-no-subscription"