---

- name: Deploy proxmox containers
  hosts: cluster
  roles:
    - services/lxc_containers
    - services/user_management

- name: Deploy proxmox services basic configuration
  hosts: services
  gather_facts: false
  roles:
    - common/dns_setup
    - common/packages

- name: Deploy proxmox services specific configuration
  hosts: services
  roles:
    - role: services/install_wireguard
      when: inventory_hostname == 'wireguard'