---

- name: Install required packages
  hosts: cluster
  gather_facts: false
  roles:
    - common/dns_setup
    - common/packages

- name: Applying basic configuration
  hosts: cluster
  roles:
    - infrastructure/power_policy
    - infrastructure/gpu_manager
    - infrastructure/proxmox_customizations
    - infrastructure/proxmox_cluster